/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.um.lms.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the author service. Represents a row in the &quot;lms_author&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.um.lms.sb.model.impl.authorModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.um.lms.sb.model.impl.authorImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see author
 * @generated
 */
@ProviderType
public interface authorModel
	extends BaseModel<author>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a author model instance should use the {@link author} interface instead.
	 */

	/**
	 * Returns the primary key of this author.
	 *
	 * @return the primary key of this author
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this author.
	 *
	 * @param primaryKey the primary key of this author
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this author.
	 *
	 * @return the uuid of this author
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this author.
	 *
	 * @param uuid the uuid of this author
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the author ID of this author.
	 *
	 * @return the author ID of this author
	 */
	public long getAuthorID();

	/**
	 * Sets the author ID of this author.
	 *
	 * @param authorID the author ID of this author
	 */
	public void setAuthorID(long authorID);

	/**
	 * Returns the group ID of this author.
	 *
	 * @return the group ID of this author
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this author.
	 *
	 * @param groupId the group ID of this author
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this author.
	 *
	 * @return the company ID of this author
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this author.
	 *
	 * @param companyId the company ID of this author
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this author.
	 *
	 * @return the user ID of this author
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this author.
	 *
	 * @param userId the user ID of this author
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this author.
	 *
	 * @return the user uuid of this author
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this author.
	 *
	 * @param userUuid the user uuid of this author
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this author.
	 *
	 * @return the user name of this author
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this author.
	 *
	 * @param userName the user name of this author
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this author.
	 *
	 * @return the create date of this author
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this author.
	 *
	 * @param createDate the create date of this author
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this author.
	 *
	 * @return the modified date of this author
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this author.
	 *
	 * @param modifiedDate the modified date of this author
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the first name of this author.
	 *
	 * @return the first name of this author
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this author.
	 *
	 * @param firstName the first name of this author
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the middle name of this author.
	 *
	 * @return the middle name of this author
	 */
	@AutoEscape
	public String getMiddleName();

	/**
	 * Sets the middle name of this author.
	 *
	 * @param middleName the middle name of this author
	 */
	public void setMiddleName(String middleName);

	/**
	 * Returns the last name of this author.
	 *
	 * @return the last name of this author
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this author.
	 *
	 * @param lastName the last name of this author
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the display name of this author.
	 *
	 * @return the display name of this author
	 */
	@AutoEscape
	public String getDisplayName();

	/**
	 * Sets the display name of this author.
	 *
	 * @param displayName the display name of this author
	 */
	public void setDisplayName(String displayName);

	/**
	 * Returns the salutation of this author.
	 *
	 * @return the salutation of this author
	 */
	@AutoEscape
	public String getSalutation();

	/**
	 * Sets the salutation of this author.
	 *
	 * @param salutation the salutation of this author
	 */
	public void setSalutation(String salutation);

}