/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.um.lms.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the lending service. Represents a row in the &quot;lms_lending&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.um.lms.sb.model.impl.lendingModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.um.lms.sb.model.impl.lendingImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see lending
 * @generated
 */
@ProviderType
public interface lendingModel
	extends BaseModel<lending>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lending model instance should use the {@link lending} interface instead.
	 */

	/**
	 * Returns the primary key of this lending.
	 *
	 * @return the primary key of this lending
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lending.
	 *
	 * @param primaryKey the primary key of this lending
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this lending.
	 *
	 * @return the uuid of this lending
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this lending.
	 *
	 * @param uuid the uuid of this lending
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the lending ID of this lending.
	 *
	 * @return the lending ID of this lending
	 */
	public long getLendingID();

	/**
	 * Sets the lending ID of this lending.
	 *
	 * @param lendingID the lending ID of this lending
	 */
	public void setLendingID(long lendingID);

	/**
	 * Returns the group ID of this lending.
	 *
	 * @return the group ID of this lending
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this lending.
	 *
	 * @param groupId the group ID of this lending
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this lending.
	 *
	 * @return the company ID of this lending
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this lending.
	 *
	 * @param companyId the company ID of this lending
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this lending.
	 *
	 * @return the user ID of this lending
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this lending.
	 *
	 * @param userId the user ID of this lending
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this lending.
	 *
	 * @return the user uuid of this lending
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this lending.
	 *
	 * @param userUuid the user uuid of this lending
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this lending.
	 *
	 * @return the user name of this lending
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this lending.
	 *
	 * @param userName the user name of this lending
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this lending.
	 *
	 * @return the create date of this lending
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this lending.
	 *
	 * @param createDate the create date of this lending
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this lending.
	 *
	 * @return the modified date of this lending
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this lending.
	 *
	 * @param modifiedDate the modified date of this lending
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the book title of this lending.
	 *
	 * @return the book title of this lending
	 */
	public long getBookTitle();

	/**
	 * Sets the book title of this lending.
	 *
	 * @param bookTitle the book title of this lending
	 */
	public void setBookTitle(long bookTitle);

	/**
	 * Returns the book ID of this lending.
	 *
	 * @return the book ID of this lending
	 */
	public long getBookId();

	/**
	 * Sets the book ID of this lending.
	 *
	 * @param bookId the book ID of this lending
	 */
	public void setBookId(long bookId);

	/**
	 * Returns the student ID of this lending.
	 *
	 * @return the student ID of this lending
	 */
	public long getStudentId();

	/**
	 * Sets the student ID of this lending.
	 *
	 * @param studentId the student ID of this lending
	 */
	public void setStudentId(long studentId);

	/**
	 * Returns the staff ID of this lending.
	 *
	 * @return the staff ID of this lending
	 */
	public long getStaffId();

	/**
	 * Sets the staff ID of this lending.
	 *
	 * @param staffId the staff ID of this lending
	 */
	public void setStaffId(long staffId);

	/**
	 * Returns the due date of this lending.
	 *
	 * @return the due date of this lending
	 */
	public Date getDueDate();

	/**
	 * Sets the due date of this lending.
	 *
	 * @param dueDate the due date of this lending
	 */
	public void setDueDate(Date dueDate);

	/**
	 * Returns the late fee of this lending.
	 *
	 * @return the late fee of this lending
	 */
	public float getLateFee();

	/**
	 * Sets the late fee of this lending.
	 *
	 * @param lateFee the late fee of this lending
	 */
	public void setLateFee(float lateFee);

	/**
	 * Returns the checkout date of this lending.
	 *
	 * @return the checkout date of this lending
	 */
	public Date getCheckoutDate();

	/**
	 * Sets the checkout date of this lending.
	 *
	 * @param checkoutDate the checkout date of this lending
	 */
	public void setCheckoutDate(Date checkoutDate);

	/**
	 * Returns the loan period of this lending.
	 *
	 * @return the loan period of this lending
	 */
	public long getLoanPeriod();

	/**
	 * Sets the loan period of this lending.
	 *
	 * @param loanPeriod the loan period of this lending
	 */
	public void setLoanPeriod(long loanPeriod);

	/**
	 * Returns the checkin date of this lending.
	 *
	 * @return the checkin date of this lending
	 */
	public Date getCheckinDate();

	/**
	 * Sets the checkin date of this lending.
	 *
	 * @param checkinDate the checkin date of this lending
	 */
	public void setCheckinDate(Date checkinDate);

}