/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.um.lms.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the student service. Represents a row in the &quot;lms_student&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.um.lms.sb.model.impl.studentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.um.lms.sb.model.impl.studentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see student
 * @generated
 */
@ProviderType
public interface studentModel
	extends BaseModel<student>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a student model instance should use the {@link student} interface instead.
	 */

	/**
	 * Returns the primary key of this student.
	 *
	 * @return the primary key of this student
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this student.
	 *
	 * @param primaryKey the primary key of this student
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this student.
	 *
	 * @return the uuid of this student
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this student.
	 *
	 * @param uuid the uuid of this student
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the student ID of this student.
	 *
	 * @return the student ID of this student
	 */
	public long getStudentID();

	/**
	 * Sets the student ID of this student.
	 *
	 * @param studentID the student ID of this student
	 */
	public void setStudentID(long studentID);

	/**
	 * Returns the group ID of this student.
	 *
	 * @return the group ID of this student
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this student.
	 *
	 * @param groupId the group ID of this student
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this student.
	 *
	 * @return the company ID of this student
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this student.
	 *
	 * @param companyId the company ID of this student
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this student.
	 *
	 * @return the user ID of this student
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this student.
	 *
	 * @param userId the user ID of this student
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this student.
	 *
	 * @return the user uuid of this student
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this student.
	 *
	 * @param userUuid the user uuid of this student
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this student.
	 *
	 * @return the user name of this student
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this student.
	 *
	 * @param userName the user name of this student
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this student.
	 *
	 * @return the create date of this student
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this student.
	 *
	 * @param createDate the create date of this student
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this student.
	 *
	 * @return the modified date of this student
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this student.
	 *
	 * @param modifiedDate the modified date of this student
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the first name of this student.
	 *
	 * @return the first name of this student
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this student.
	 *
	 * @param firstName the first name of this student
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the middle name of this student.
	 *
	 * @return the middle name of this student
	 */
	@AutoEscape
	public String getMiddleName();

	/**
	 * Sets the middle name of this student.
	 *
	 * @param middleName the middle name of this student
	 */
	public void setMiddleName(String middleName);

	/**
	 * Returns the last name of this student.
	 *
	 * @return the last name of this student
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this student.
	 *
	 * @param lastName the last name of this student
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the display name of this student.
	 *
	 * @return the display name of this student
	 */
	@AutoEscape
	public String getDisplayName();

	/**
	 * Sets the display name of this student.
	 *
	 * @param displayName the display name of this student
	 */
	public void setDisplayName(String displayName);

	/**
	 * Returns the salutation of this student.
	 *
	 * @return the salutation of this student
	 */
	@AutoEscape
	public String getSalutation();

	/**
	 * Sets the salutation of this student.
	 *
	 * @param salutation the salutation of this student
	 */
	public void setSalutation(String salutation);

	/**
	 * Returns the department ID of this student.
	 *
	 * @return the department ID of this student
	 */
	@AutoEscape
	public String getDepartmentID();

	/**
	 * Sets the department ID of this student.
	 *
	 * @param departmentID the department ID of this student
	 */
	public void setDepartmentID(String departmentID);

	/**
	 * Returns the batch of this student.
	 *
	 * @return the batch of this student
	 */
	@AutoEscape
	public String getBatch();

	/**
	 * Sets the batch of this student.
	 *
	 * @param batch the batch of this student
	 */
	public void setBatch(String batch);

	/**
	 * Returns the duration of this student.
	 *
	 * @return the duration of this student
	 */
	public long getDuration();

	/**
	 * Sets the duration of this student.
	 *
	 * @param duration the duration of this student
	 */
	public void setDuration(long duration);

	/**
	 * Returns the registration no of this student.
	 *
	 * @return the registration no of this student
	 */
	public long getRegistrationNo();

	/**
	 * Sets the registration no of this student.
	 *
	 * @param registrationNo the registration no of this student
	 */
	public void setRegistrationNo(long registrationNo);

}