/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.um.lms.sb.model.impl;

import com.um.lms.sb.model.publication;
import com.um.lms.sb.service.publicationLocalServiceUtil;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The extended model base implementation for the publication service. Represents a row in the &quot;lms_publication&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link publicationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see publicationImpl
 * @see publication
 * @generated
 */
@ProviderType
public abstract class publicationBaseImpl
	extends publicationModelImpl implements publication {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a publication model instance should use the <code>publication</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			publicationLocalServiceUtil.addpublication(this);
		}
		else {
			publicationLocalServiceUtil.updatepublication(this);
		}
	}

}